#Download base image ubuntu 16.04
FROM ubuntu:16.04

# Update Ubuntu Software repository
RUN apt-get update

# Install python and jupyter
RUN apt-get install -y python3 python2 

RUN pip3 install --upgrade pip
RUN apt install python3-pip
RUN apt install python2-pip
RUN pip3 install jupyter
RUN pip install ec3-cli

# Install git
RUN pat-get install git

# Clone git
RUN git clone https://github.com/grycap/apricot.git

# Install apricot
RUN bash apricot/install.sh
